# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignGui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class DesignGui(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 470)
        Dialog.setMinimumSize(QtCore.QSize(600, 470))
        Dialog.setMaximumSize(QtCore.QSize(600, 470))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pinionStrengthLabel = QtWidgets.QLabel(Dialog)
        self.pinionStrengthLabel.setObjectName("pinionStrengthLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pinionStrengthLabel)
        self.pinionStrength = QtWidgets.QDoubleSpinBox(Dialog)
        self.pinionStrength.setMinimum(1.0)
        self.pinionStrength.setMaximum(10000000.0)
        self.pinionStrength.setObjectName("pinionStrength")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pinionStrength)
        self.gearStrengthLabel = QtWidgets.QLabel(Dialog)
        self.gearStrengthLabel.setObjectName("gearStrengthLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gearStrengthLabel)
        self.gearStrength = QtWidgets.QDoubleSpinBox(Dialog)
        self.gearStrength.setMinimum(1.0)
        self.gearStrength.setMaximum(10000000.0)
        self.gearStrength.setObjectName("gearStrength")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gearStrength)
        self.pinionElasticityLabel = QtWidgets.QLabel(Dialog)
        self.pinionElasticityLabel.setObjectName("pinionElasticityLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pinionElasticityLabel)
        self.pinionElasticity = QtWidgets.QDoubleSpinBox(Dialog)
        self.pinionElasticity.setMinimum(1.0)
        self.pinionElasticity.setMaximum(10000000.0)
        self.pinionElasticity.setObjectName("pinionElasticity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pinionElasticity)
        self.gearElasticityLabel = QtWidgets.QLabel(Dialog)
        self.gearElasticityLabel.setObjectName("gearElasticityLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gearElasticityLabel)
        self.gearElasticity = QtWidgets.QDoubleSpinBox(Dialog)
        self.gearElasticity.setMinimum(1.0)
        self.gearElasticity.setMaximum(10000000.0)
        self.gearElasticity.setObjectName("gearElasticity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gearElasticity)
        self.gradeLabel = QtWidgets.QLabel(Dialog)
        self.gradeLabel.setObjectName("gradeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gradeLabel)
        self.grade = QtWidgets.QComboBox(Dialog)
        self.grade.setObjectName("grade")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.grade)
        self.profileLabel = QtWidgets.QLabel(Dialog)
        self.profileLabel.setObjectName("profileLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.profileLabel)
        self.profile = QtWidgets.QComboBox(Dialog)
        self.profile.setObjectName("profile")
        self.profile.addItem("")
        self.profile.addItem("")
        self.profile.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.profile)
        self.pinionTeethLabel = QtWidgets.QLabel(Dialog)
        self.pinionTeethLabel.setObjectName("pinionTeethLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pinionTeethLabel)
        self.pinionTeeth = QtWidgets.QSpinBox(Dialog)
        self.pinionTeeth.setMinimum(14)
        self.pinionTeeth.setMaximum(300)
        self.pinionTeeth.setObjectName("pinionTeeth")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pinionTeeth)
        self.gearTeethLabel = QtWidgets.QLabel(Dialog)
        self.gearTeethLabel.setObjectName("gearTeethLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.gearTeethLabel)
        self.gearTeeth = QtWidgets.QSpinBox(Dialog)
        self.gearTeeth.setMinimum(14)
        self.gearTeeth.setMaximum(300)
        self.gearTeeth.setObjectName("gearTeeth")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.gearTeeth)
        self.powerLabel = QtWidgets.QLabel(Dialog)
        self.powerLabel.setObjectName("powerLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.powerLabel)
        self.power = QtWidgets.QDoubleSpinBox(Dialog)
        self.power.setMinimum(1.0)
        self.power.setMaximum(1000000.0)
        self.power.setObjectName("power")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.power)
        self.pinionRpmLabel = QtWidgets.QLabel(Dialog)
        self.pinionRpmLabel.setObjectName("pinionRpmLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pinionRpmLabel)
        self.pinionRpm = QtWidgets.QDoubleSpinBox(Dialog)
        self.pinionRpm.setMinimum(1.0)
        self.pinionRpm.setMaximum(10000.0)
        self.pinionRpm.setObjectName("pinionRpm")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pinionRpm)
        self.gearingLabel = QtWidgets.QLabel(Dialog)
        self.gearingLabel.setObjectName("gearingLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.gearingLabel)
        self.gearing = QtWidgets.QComboBox(Dialog)
        self.gearing.setObjectName("gearing")
        self.gearing.addItem("")
        self.gearing.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.gearing)
        self.safetyFactorLabel = QtWidgets.QLabel(Dialog)
        self.safetyFactorLabel.setObjectName("safetyFactorLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.safetyFactorLabel)
        self.safetyFactor = QtWidgets.QDoubleSpinBox(Dialog)
        self.safetyFactor.setMinimum(1.0)
        self.safetyFactor.setMaximum(10.0)
        self.safetyFactor.setObjectName("safetyFactor")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.safetyFactor)
        self.serviceFactorLabel = QtWidgets.QLabel(Dialog)
        self.serviceFactorLabel.setObjectName("serviceFactorLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.serviceFactorLabel)
        self.serviceFactor = QtWidgets.QDoubleSpinBox(Dialog)
        self.serviceFactor.setMinimum(1.0)
        self.serviceFactor.setMaximum(10.0)
        self.serviceFactor.setObjectName("serviceFactor")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.serviceFactor)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Design Data"))
        self.pinionStrengthLabel.setText(_translate("Dialog", "Enter ultimate tensile strength of pinion N.mm^-2"))
        self.gearStrengthLabel.setText(_translate("Dialog", "Enter ultimate tensile strength of gear N.mm^-2"))
        self.pinionElasticityLabel.setText(_translate("Dialog", "Enter modulus of elasticity of pinion N.mm^-2"))
        self.gearElasticityLabel.setText(_translate("Dialog", "Enter modulus of elasticity of gear N.mm^-2"))
        self.gradeLabel.setText(_translate("Dialog", "Select grade of gear pair"))
        self.grade.setItemText(0, _translate("Dialog", "1"))
        self.grade.setItemText(1, _translate("Dialog", "2"))
        self.grade.setItemText(2, _translate("Dialog", "3"))
        self.grade.setItemText(3, _translate("Dialog", "4"))
        self.grade.setItemText(4, _translate("Dialog", "5"))
        self.grade.setItemText(5, _translate("Dialog", "6"))
        self.grade.setItemText(6, _translate("Dialog", "7"))
        self.grade.setItemText(7, _translate("Dialog", "8"))
        self.grade.setItemText(8, _translate("Dialog", "9"))
        self.grade.setItemText(9, _translate("Dialog", "10"))
        self.grade.setItemText(10, _translate("Dialog", "11"))
        self.grade.setItemText(11, _translate("Dialog", "12"))
        self.profileLabel.setText(_translate("Dialog", "Select type of gear pair"))
        self.profile.setItemText(0, _translate("Dialog", "14.5 degree full depth involute tooth"))
        self.profile.setItemText(1, _translate("Dialog", "20 degree full depth involute tooth"))
        self.profile.setItemText(2, _translate("Dialog", "20 degree stub involute tooth"))
        self.pinionTeethLabel.setText(_translate("Dialog", "Enter number of pinion teeth"))
        self.gearTeethLabel.setText(_translate("Dialog", "Enter number of gear teeth"))
        self.powerLabel.setText(_translate("Dialog", "Enter power transmitted by gear pair W"))
        self.pinionRpmLabel.setText(_translate("Dialog", "Enter speed of pinion rpm"))
        self.gearingLabel.setText(_translate("Dialog", "Enter type of gearing"))
        self.gearing.setItemText(0, _translate("Dialog", "Internal gearing"))
        self.gearing.setItemText(1, _translate("Dialog", "External gearing"))
        self.safetyFactorLabel.setText(_translate("Dialog", "Enter factor of safety"))
        self.serviceFactorLabel.setText(_translate("Dialog", "Enter service factor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = DesignGui()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
